### ISSUE TITLE
How to convert a tiff file to wsi dicom file using this repo ? 

### ISSUE THREAD

**Issue by saikrishnaksbs** [ImagingDataCommons/idc-wsi-conversion#3]

**Comment by fedorov** [comment]
We do not have a detailed tutorial, but perhaps this notebook could be helpful - it has the steps and example conversion: https://colab.research.google.com/drive/1sbuGggwmbE-JgkO8LS5ndXIzLpf7yhKd?usp=sharing#scrollTo=xn13pTy62joU (developed as part of the project here: https://projectweek.na-mic.org/PW38_2023_GranCanaria/Projects/IDC_DICOM_WSI_workflow/).

**Comment by saikrishnaksbs** [comment]
Thankyou fedorov
